### ISSUE TITLE
Test with Covariate tool

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmr#114]
Hi All,

I tried to run the Cov tool for a very simple Pk model:

![image](https://user-images.githubusercontent.com/75624013/191027176-e5d3c0b2-e687-4dd3-b48b-705d54b9cb45.png)

$PROBLEM PERIPHERALS(1);PERIPHERALS(2)
$INPUT C FLAG STDY ID TIME TIMESCHED TADSCHED TIMD AMT RATE DV EVID TYPE TRT HB HEMOL WGT DIS
$DATA dataset_filtered.csv IGNORE=@
$SUBROUTINES ADVAN11  TRANS4 
$PK
VP2 = THETA(6)
QP2 = THETA(5)
VP1 = THETA(4)
QP1 = THETA(3)
VC = THETA(1) * EXP(ETA(1))
CL = THETA(2) * EXP(ETA(2))
V1 = VC
Q2 = QP1
V2 = VP1
Q3 = QP2
V3 = VP2
$ERROR
IF (A(1)/VC.EQ.0) THEN
    IPREDADJ = 2.22500000000000E-16
ELSE
    IPREDADJ = A(1)/VC
END IF
Y = A(1)/VC + EPS(1)*IPREDADJ
$ESTIMATION METHOD=COND INTERACTION MAXEVAL=9999 SADDLE_RESET=1 
$TABLE ID TIME CWRES CIPREDI DV PRED RES WRES IPREDI IWRESI FILE=mytab NOAPPEND NOPRINT
$THETA (0, 3.99232, Inf) ; POP_VC
$THETA (0, 0.0237094, Inf) ; POP_CL
$THETA  (0,0.00235761,999999) ; POP_QP1
$THETA  (0,6.44806,999999) ; POP_VP1
$THETA  (0,0.02121849,999999) ; POP_QP2
$THETA  (0,6.44806,999999) ; POP_VP2
$OMEGA BLOCK(2)
0.0554123	; IIV_VC
0.0370828	; IIV_VC_IIV_CL
0.0902628	; IIV_CL
$SIGMA  0.0312138 ; sigma

Using the following code:
> #Run the COV search
res <- run_covsearch(algorithm='scm-forward',
                     model=input_model,
                     effects='COVARIATE([CL, V], [WGT], EXP)',
                     p_forward=0.01,
                     max_steps=5)

I'm however facing an error (see below).
In addition, when I'm look into the ouput files, it is empty with no error messages.

2022-09-19 13:28:37,431 - distributed.worker - WARNING - Compute Failed
Key:       forward-search-init-results
Function:  execute_task
args:      ((<function task_results at 0x7f7c56d889d0>, (<function task_greedy_forward_search at 0x7f7c56d885e0>, 'COVARIATE([CL, V], [WGT], EXP)', 0.01, 5.0, (<function _init_search_state at 0x7f7c56d88430>, <Pharmpy model object run1>))))
kwargs:    {}
Exception: 'TypeError("\'float\' object cannot be interpreted as an integer")'

<Client: 'inproc://172.17.0.18/334/10' processes=1 threads=12, memory=31.24 GiB>
TypeError: 'float' object cannot be interpreted as an integer
Full stack:
TypeError'float' object cannot be interpreted as an integerc("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/wrap.py\", line 46, in _func\n    return run_tool(tool_name, *args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 170, in run_tool\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 58, in execute_workflow\n    res = dispatcher.run(workflow)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 40, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3052, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py\", line 216, in task_greedy_forward_search\n    return _greedy_search(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py\", line 264, in _greedy_search\n    steps = range(1, max_steps + 1) if max_steps >= 0 else count(1)\n"
)Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/wrap.py", line 46, in _func
    return run_tool(tool_name, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 170, in run_tool
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 58, in execute_workflow
    res = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 40, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3052, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py", line 216, in task_greedy_forward_search
    return _greedy_search(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py", line 264, in _greedy_search
    steps = range(1, max_steps + 1) if max_steps >= 0 else count(1)
TypeError: 'float' object cannot be interpreted as an integer

pharmr version: 0.76.5
'0.76.5'
Pharmpy version: 0.76.5

**Comment by stellabelin** [comment]
Hi! Thank you for reporting! This is an error that occurs due to how R handles integers compared to Python, currently we can't convert it automatically. We have it documented [here](https://pharmpy.github.io/latest/using_r.html#floats-and-integers), see issue  #80. In this example, you'd have to do: 

```
res <- run_covsearch(..., max_steps=5L)
```

**Comment by SimonBuatois** [comment]
Hi I tried and have the same message:

> res <- run_covsearch(algorithm='scm-forward',
+                      model=input_model,
+                      effects='COVARIATE([CL, V], [WGT], EXP)',
+                      p_forward=0.01,
+                      max_steps=5L)
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: run1+1: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: run1+2: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
2022-09-19 15:19:50,012 - distributed.worker - WARNING - Compute Failed
Key:       V', 'WGT', 'exp', '*-run1-fd275503-2111-40fa-b3fa-f79a27f98404
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x7f7c475aa790>, (<function task_add_covariate_effect at 0x7f7c56d88820>, <Pharmpy model object run1>, ('V', 'WGT', 'exp', '*'), 2)))
kwargs:    {}
Exception: 'ValueError()'

2022-09-19 15:19:50,219 - distributed.worker - WARNING - Compute Failed
Key:       forward-search-init-results
Function:  execute_task
args:      ((<function task_results at 0x7f7c56d889d0>, (<function task_greedy_forward_search at 0x7f7c56d885e0>, 'COVARIATE([CL, V], [WGT], EXP)', 0.01, 5, (<function _init_search_state at 0x7f7c56d88430>, <Pharmpy model object run1>))))
kwargs:    {}
Exception: 'ValueError()'

<Client: 'inproc://172.17.0.18/334/18' processes=1 threads=12, memory=31.24 GiB>
ValueError
Full stack:
ValueErrorc("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/wrap.py\", line 46, in _func\n    return run_tool(tool_name, *args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 170, in run_tool\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 58, in execute_workflow\n    res = dispatcher.run(workflow)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 40, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3052, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py\", line 216, in task_greedy_forward_search\n    return _greedy_search(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py\", line 270, in _greedy_search\n    new_candidates = handle_effects(step, best_candidate_so_far, candidate_effects)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py\", line 209, in handle_effects\n    new_candidate_models = call_workflow(wf, f'{NAME_WF}-effects_addition-{step}')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 133, in call_workflow\n    res = client.gather(futures)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py\", line 329, in task_add_covariate_effect\n    add_covariate_effect(model_with_added_effect, *effect)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/covariate_effect.py\", line 163, in add_covariate_effect\n    insertion_index = sset.index(last_existing_parameter_assignment) + 1\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/_collections_abc.py\", line 911, in index\n    raise ValueError\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/wrap.py", line 46, in _func
    return run_tool(tool_name, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 170, in run_tool
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 58, in execute_workflow
    res = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 40, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3052, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py", line 216, in task_greedy_forward_search
    return _greedy_search(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py", line 270, in _greedy_search
    new_candidates = handle_effects(step, best_candidate_so_far, candidate_effects)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py", line 209, in handle_effects
    new_candidate_models = call_workflow(wf, f'{NAME_WF}-effects_addition-{step}')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 133, in call_workflow
    res = client.gather(futures)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py", line 329, in task_add_covariate_effect
    add_covariate_effect(model_with_added_effect, *effect)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/covariate_effect.py", line 163, in add_covariate_effect
    insertion_index = sset.index(last_existing_parameter_assignment) + 1
  File "/miniconda/envs/r-reticulate/lib/python3.8/_collections_abc.py", line 911, in index
    raise ValueError
ValueError

pharmr version: 0.76.5
'0.76.5'
Pharmpy version: 0.76.5

**Comment by pharmpy-dev-123** [comment]
@SimonBuatois That's a different error. We will look into it.

**Comment by pharmpy-dev-123** [comment]
@SimonBuatois The error probably comes from `V` not being defined in the model. There is only `V1`, `V2`, `V3`, etc. We should raise an error with a better message in this case in the future. Did you expect Pharmpy to pick up all these volume definitions by only specifying `V`?

**Comment by SimonBuatois** [comment]
Thanks a lot for your reply.
The model is know running.

Knowing that the model is automatically created by pharmpy one might not be aware of the name that is being used for the central volume. In addition, the error message is difficult to understand. I would therefore recommend to increase clarity of the error model and harmonize the naming convention for models created by phampy (e.g. always use VC or V1 including in models with only one compartment and in the documentation).

Kind regards,
Simon

**Comment by rikardn** [comment]
We are working on finding these input errors before starting the tool and give clearer error messages in the PR mentioned above. The naming convention is already harmonized. We always use `VC` as in this case. `V1` is created because NONMEM needs it for the particular ADVAN being used. Please let us know if you find any exceptions to this.
