### ISSUE TITLE
ValueError: Invalid `effects` because of invalid covariate found in effects: got `D`, must be in ['C', 'DIS', 'FLAG', 'HB', 'HEMOL', 'OCC', 'RATE', 'STDY', 'TADSCHED', 'TIMD', 'TIMESCHED', 'TRT', 'TYPE', 'WGT'].

### ISSUE THREAD

**Issue by cossonvalerie** [pharmpy/pharmr#126]
After running run_amd with dataset2 (Phase 3/dataset2_14NOV2022), with Pharmpy 0.83.0.

I run the AMD tool with the following arguments
res <- run_amd(
     dataset_path,
     modeltype='pk_iv',
     search_space='PERIPHERALS([1,2]);ELIMINATION([MM,MIX-FO-MM])',
     order=c('structural', 'iivsearch', 'residual', 'iovsearch','allometry', 'covariates'),
     cl_init= CL,
     vc_init= V,
     allometric_variable = c('WGT'),
     categorical = c('DIS'),
     occasion='OCC'
     # mat_init=0.1,
     # occasion='VISI',
)

It crashes during the covariate search with the following message
ValueError: Invalid `effects` because of invalid covariate found in effects: got `D`, must be in ['C', 'DIS', 'FLAG', 'HB', 'HEMOL', 'OCC', 'RATE', 'STDY', 'TADSCHED', 'TIMD', 'TIMESCHED', 'TRT', 'TYPE', 'WGT'].

Can you help?

See the message details
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
<Client: 'inproc://172.17.0.9/336/1' processes=1 threads=1, memory=46.99 GiB>
<Client: 'inproc://172.17.0.9/336/10' processes=1 threads=1, memory=46.99 GiB>
<Client: 'inproc://172.17.0.9/336/19' processes=1 threads=1, memory=46.99 GiB>
<Client: 'inproc://172.17.0.9/336/28' processes=1 threads=1, memory=46.99 GiB>
<Client: 'inproc://172.17.0.9/336/38' processes=1 threads=1, memory=46.99 GiB>
<Client: 'inproc://172.17.0.9/336/47' processes=1 threads=1, memory=46.99 GiB>
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run2.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run1.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run5: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run5.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run7.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run4: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run4.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run6.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run12: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run12.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run11: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run11.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run10.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run9.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
ValueError: Invalid `effects` because of invalid covariate found in effects: got `D`, must be in ['C', 'DIS', 'FLAG', 'HB', 'HEMOL', 'OCC', 'RATE', 'STDY', 'TADSCHED', 'TIMD', 'TIMESCHED', 'TRT', 'TYPE', 'WGT'].
Full stack:
ValueErrorInvalid `effects` because of invalid covariate found in effects: got `D`, must be in ['C', 'DIS', 'FLAG', 'HB', 'HEMOL', 'OCC', 'RATE', 'STDY', 'TADSCHED', 'TIMD', 'TIMESCHED', 'TRT', 'TYPE', 'WGT'].c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 154, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 318, in _run_covariates\n    res = run_tool('covsearch', covariates_search_space, model=model, path=path / 'covsearch')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 177, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 193, in run_tool_with_name\n    validate_input(*args, **tool_options)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/internals/fn/type.py\", line 42, in _wrapped\n    return fn(*args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/internals/fn/signature.py\", line 50, in _wrapped\n    return fn(*permuted)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py\", line 581, in validate_input\n    raise ValueError(\n"
)Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 154, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 318, in _run_covariates
    res = run_tool('covsearch', covariates_search_space, model=model, path=path / 'covsearch')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 177, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 193, in run_tool_with_name
    validate_input(*args, **tool_options)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/internals/fn/type.py", line 42, in _wrapped
    return fn(*args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/internals/fn/signature.py", line 50, in _wrapped
    return fn(*permuted)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/covsearch/tool.py", line 581, in validate_input
    raise ValueError(
ValueError: Invalid `effects` because of invalid covariate found in effects: got `D`, must be in ['C', 'DIS', 'FLAG', 'HB', 'HEMOL', 'OCC', 'RATE', 'STDY', 'TADSCHED', 'TIMD', 'TIMESCHED', 'TRT', 'TYPE', 'WGT'].

pharmr version: 0.83.0
'0.83.0'

**Comment by stellabelin** [comment]
Hi! Thanks for reporting! This looks like it's due to the fact that it's a single length vector (issue #105). A current workaround is to do: 

```
res <- run_amd(
...
allometric_variable = list('WGT'),
categorical = list('DIS'),
...
)
```

I'm working on a way to automatically handle this in the wrapper functions so that the user does not have to use this workaround. Please let me know if the workaround does not work!

**Comment by cossonvalerie** [comment]
Thank you Stella

**Comment by joaoabr** [comment]
Another issue in this example when list() is used:
```
txt> #initial parameters
txt> CL  = 0.05 
txt> V   = 5 
txt> 
txt> #run Automatic Model Development (AMD) tool
txt> res <- run_amd(
txt+     dataset_path,
txt+     modeltype='pk_iv',
txt+     search_space='PERIPHERALS([1,2]);ELIMINATION([MM,MIX-FO-MM])',
txt+     order=c('structural', 'iivsearch', 'residual', 'iovsearch','allometry', 'covariates'),
txt+     cl_init= CL,
txt+     vc_init= V,
txt+     allometric_variable = list('WGT'),
txt+     categorical = list('DIS'),
txt+     occasion='OCC'
txt+     # mat_init=0.1,
txt+     # occasion='VISI',
txt+ )
```

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
<Client: 'inproc://172.17.0.6/336/1' processes=1 threads=1, memory=46.99 GiB>
<Client: 'inproc://172.17.0.6/336/10' processes=1 threads=1, memory=46.99 GiB>
<Client: 'inproc://172.17.0.6/336/19' processes=1 threads=1, memory=46.99 GiB>
<Client: 'inproc://172.17.0.6/336/28' processes=1 threads=1, memory=46.99 GiB>
<Client: 'inproc://172.17.0.6/336/38' processes=1 threads=1, memory=46.99 GiB>
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run2.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run1.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run5: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run5.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run7.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run4: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run4.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run6.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run12: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run12.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run11: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run11.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run10.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run9.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
TypeError: Invalid `allometric_variable`: got `['WGT']` of type <class 'list'>, expected typing.Union[str, sympy.core.expr.Expr]
Full stack:
TypeErrorInvalid `allometric_variable`: got `['WGT']` of type <class 'list'>, expected typing.Union[str, sympy.core.expr.Expr]c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 154, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 341, in _run_allometry\n    res = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 177, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 193, in run_tool_with_name\n    validate_input(*args, **tool_options)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/internals/fn/type.py\", line 33, in _wrapped\n    raise TypeError(\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 154, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 341, in _run_allometry
    res = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 177, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 193, in run_tool_with_name
    validate_input(*args, **tool_options)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/internals/fn/type.py", line 33, in _wrapped
    raise TypeError(
TypeError: Invalid `allometric_variable`: got `['WGT']` of type <class 'list'>, expected typing.Union[str, sympy.core.expr.Expr]

pharmr version: 0.83.0
'0.83.0'
Pharmpy version: 0.83.0

```

The dataset looks like this:
![image](https://user-images.githubusercontent.com/75365723/202449563-3d6d9e7d-a83f-455c-90fd-92bf8aca2af9.png)

**Comment by stellabelin** [comment]
Hi! Sorry, I was a bit hasty when changing, it should be `allometric_variable=c('WGT')` or  `allometric_variable='WGT'`

**Comment by pharmpy-dev-123** [comment]
See #105 for the automatic conversion of single element vectors function parameters. I am going to make sure the "invalid covariate found" error gets caught at the beginning of `run_amd`. This also concerns pharmpy so I'll move the issue to the relevant repo.
