### ISSUE TITLE
Problems with default value of run_ruvsearch

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmr#128]
Using default value for `run_ruvsearch` crashes:

```
TypeError: Invalid `groups`: got `4.0` of type <class 'float'>, expected <class 'int'>
Full stack:
TypeErrorInvalid `groups`: got `4.0` of type <class 'float'>, expected <class 'int'>c("  File \"/home/rikard/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/wrap.py\", line 35, in func\n    return run_tool(tool_name, *args, **kwargs)\n", "  File \"/home/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py\", line 177, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", "  File \"/home/rikard/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py\", line 193, in run_tool_with_name\n    validate_input(*args, **tool_options)\n", 
"  File \"/home/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/internals/fn/type.py\", line 33, in _wrapped\n    raise TypeError(\n")Traceback (most recent call last):
  File "/home/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/wrap.py", line 35, in func
    return run_tool(tool_name, *args, **kwargs)
  File "/home/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py", line 177, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "/home/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py", line 193, in run_tool_with_name
    validate_input(*args, **tool_options)
  File "/home/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/internals/fn/type.py", line 33, in _wrapped
    raise TypeError(
TypeError: Invalid `groups`: got `4.0` of type <class 'float'>, expected <class 'int'>
```

**Comment by pharmpy-dev-123** [comment]
Same as #78. I think handling these default values is part of the discussion in #80.

**Comment by rikardn** [comment]
Fixed in pywrapr
