### ISSUE TITLE
Evaluate input arguments to wrapper functions

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmr#129]
Since R uses lazy loading, if there is e.g. a misspelling of a variable name or if a function is given as an argument it will not be evaluated until needed (seems to happen when converting in reticulate). The subsequent error includes the R-error (which we want) and a stack trace that is irrelevant to the user. If all input arguments are evaluated (e.g. `x; y; z`) before calling Python we can get the correct R-error.

**Comment by rikardn** [comment]
Example error message for the lazy evaluation shenanigans:

```
object 'rs1' not foundFull stack:
IndexErroronly integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices  File "/home/rikard/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 935, in __getitem__
    raise IndexError(
Traceback (most recent call last):
  File "/home/rikard/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 935, in __getitem__
    raise IndexError(
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
