### ISSUE TITLE
AMD crash at stage RUV search

### ISSUE THREAD

**Issue by artikandms** [pharmpy/pharmr#167]
Hi ! 
AMD crash at stage RUV search with a basic type pk model. All the steps before seem to work well. I think I saw on the forum that this problem exists with the models of type pk/ pd but I'm not sure. Do you have an explanation? 
I am sending you my error message. Thank you again. 
<img width="508" alt="amdruvsearch" src="https://github.com/pharmpy/pharmr/assets/166139814/d949c4b0-710b-41c9-8eef-5f015862561d">

**Comment by stellabelin** [comment]
Hi! This is a known issue that we have a workaround for, which version of Pharmpy/pharmr are you running (`pharmr::print_pharmpy_version()`)?

**Comment by artikandms** [comment]
I'm running the 0.108.0 version !

**Comment by stellabelin** [comment]
Okay, I suspect the version of `dask` is incompatible, we have a fix for this in the next release. Could check which version of `dask` you are using with the command `reticulate::py_list_packages()`? The output will look something like:

```
                          package    version                         requirement   channel
1                   _libgcc_mutex        0.1                   _libgcc_mutex=0.1 pkgs/main
2                   _openmp_mutex        5.1                   _openmp_mutex=5.1 pkgs/main
3                       alabaster     0.7.13                    alabaster=0.7.13      pypi
4                          altair      5.0.1                        altair=5.0.1      pypi
...
23                           dask   2024.4.2                       dask=2024.4.2      pypi
...
```
If the version of `dask<=2024.4.1` it should work that you update Pharmpy/pharmr to 0.109.0. If not or if you want to keep using 0.108.0 you need to downgrade dask, let me know if that's the case and I can point you toward how to do this. In the next release of Pharmpy all newer `dask` versions should be supported

**Comment by artikandms** [comment]
Hello again. I updated pharmpy / pharmr to 0.109.0 because I had dask = 2024.4.0.
I still have an error, this time at iiv search : 
```
res <- run_amd(input = 'warf_sans_cmt.csv',
                modeltype = 'basic_pk',
               administration = 'oral',
               strategy = "default",
               cl_init = 0.130,
               vc_init = 8,
               mat_init = 3,
               allometric_variable = 'WGT',
               strictness = 'minimization_successful and rse < 0.5',
               retries_strategy = "all_final",
               parameter_uncertainty_method = 'SANDWICH')
```

Here is my error message : 
2024-04-26 12:08:10,895 - distributed.worker - WARNING - Compute Failed
Key:       results_top_down_exhaustive
Function:  post_process
args:      ('mbic', None, 'minimization_successful and rse < 0.5', <pharmpy.workflows.model_entry.ModelEntry object at 0x7f6d6c77a5d0>, 'base_model', 'td_exhaustive_no_of_etas', <pharmpy.workflows.model_entry.ModelEntry object at 0x7f6d49eed580>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7f6d49c92b10>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7f6dc14de960>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7f6d8440c1a0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7f6d6c53c770>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7f6dc12de9c0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7f6dc1749ca0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7f6d48d199d0>)
kwargs:    {}
Exception: "ValueError('All models fail the strictness criteria!')"

2024-04-26 12:08:10,909 - distributed.worker - WARNING - Compute Failed
Key:       start_iiv-results
Function:  execute_task
args:      ((<function _results at 0x7f6d488f3420>, (<function start at 0x7f6d84238cc0>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x7f6dc12deae0>, <Pharmpy model object structural_retries_run3>, <Pharmpy modelfit results object structural_retries_run3>, 'top_down_exhaustive', None, 'fullblock', 'mbic', None, ['CL'], 'minimization_successful and rse < 0.5')))
kwargs:    {}
Exception: "ValueError('All models fail the strictness criteria!')"

ValueError: All models fail the strictness criteria!
Run `reticulate::py_last_error()` for details.Full stack:
ValueErrorAll models fail the strictness criteria!c("  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/amd/run.py\", line 476, in run_amd\n    subresults = func(next_model, next_res)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/amd/run.py\", line 805, in _run_iiv\n    res = run_tool(\n          ^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/run.py\", line 169, in run_tool\n    return run_tool_with_name(name, tool, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/run.py\", line 207, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, database=tool_database)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/workflows/execute.py\", line 73, in execute_workflow\n    res: T = dispatcher.run(workflow)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 84, in run\n    res = client.get(dsk_optimized, 'results')\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/distributed/client.py\", line 3275, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/distributed/client.py\", line 2372, in gather\n    return self.sync(\n           ^^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/iivsearch/tool.py\", line 247, in start\n    res = call_workflow(wf, f'results_{algorithm}', context)\n    ^^^^^^^^^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/workflows/call.py\", line 42, in call_workflow\n    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]\n      ^^^^^^^^^^^^^^^^^\n", 
"  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/iivsearch/tool.py\", line 426, in post_process\n    res = create_results(\n      ^^^^^^^^^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/common.py\", line 85, in create_results\n    summary_tool = summarize_tool(\n      ^^^^^^^^^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/common.py\", line 218, in summarize_tool\n    raise ValueError(\"All models fail the strictness criteria!\")\n    ^^^^^^^^^^^^^^^^^\n"
)Traceback (most recent call last):
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/amd/run.py", line 476, in run_amd
    subresults = func(next_model, next_res)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/amd/run.py", line 805, in _run_iiv
    res = run_tool(
          ^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/run.py", line 169, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/run.py", line 207, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=tool_database)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/workflows/execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 84, in run
    res = client.get(dsk_optimized, 'results')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/distributed/client.py", line 3275, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/distributed/client.py", line 2372, in gather
    return self.sync(
           ^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/iivsearch/tool.py", line 247, in start
    res = call_workflow(wf, f'results_{algorithm}', context)
    ^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/workflows/call.py", line 42, in call_workflow
    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]
      ^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/iivsearch/tool.py", line 426, in post_process
    res = create_results(
      ^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/common.py", line 85, in create_results
    summary_tool = summarize_tool(
      ^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/common.py", line 218, in summarize_tool
    raise ValueError("All models fail the strictness criteria!")
    ^^^^^^^^^^^^^^^^^
ValueError: All models fail the strictness criteria!
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.ValueError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(input = "warf_sans_cmt.csv", modeltype = "basic_pk", administration = "oral", strategy = "default", cl_init = 0.13, vc_init = 8, mat_init = 3, allometric_variable = "WGT", strictness = "minimization_successful and rse < 0.5", retries_strategy = "all_final", parameter_uncertainty_method = "SANDWICH"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.model.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}, warning = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(input = "warf_sans_cmt.csv", modeltype = "basic_pk", administration = "oral", 
    strategy = "default", cl_init = 0.13, vc_init = 8, mat_init = 3, allometric_variable = "WGT", strictness = "minimization_successful and rse < 0.5", retries_strategy = "all_final", parameter_uncertainty_method = "SANDWICH"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.model.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}, warning = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 0.109.0
'0.109.0'
Pharmpy version: 0.109.0

**Comment by artikandms** [comment]
I updated pharmr to 0.109 because I had dask = 2024.4.0 and that fixed my AMD problem. Thank you !
However, my error messages are much longer and more detailed, is this normal?

**Comment by stellabelin** [comment]
Hi! Just to double check, you're running the exact same command as in 0.108.0? The error is related to the fact that no candidate model fulfilled your strictness criteria (we have on the agenda to have this as a clearer error). Maybe you can check the file `results.csv` from your iivsearch run in 0.108.0 and check if it created the same number of models as in 0.109.0. Does the input model (found in the iivsearch directory under `models/input_model/input_model.ctl`) look the same in both versions?

**Comment by artikandms** [comment]
Sorry I wasn't very clear, my AMD problem is now fixed with the new version. I just noticed that in general, if I have error messages, they are longer and more detailed. I don't know if it's a version "problem". I would like to close the conversation so as not to disturb you further. Thank you for your precious help every time. I am aware of the time it takes.

**Comment by stellabelin** [comment]
Hi! How long the error messages are is dependent on where the error occurs (within or outside a workflow), so it could also affect! And no problem!
