### ISSUE TITLE
AMD error in pharmr 1.0.1

### ISSUE THREAD

**Issue by hugo-maas** [pharmpy/pharmr#174]
Hi,

This is the second of a couple of errors we experienced when running an example pharmr script on our system (pharmpy/pharmr 1.0.1, reticulate 1.38.0, R version 4.4.1, Python 3.11.3, numpy 2.0.1, gcc 12.3.0).

```

# the AMD work flow ####
## from a dataset ####
amd.result <- run_amd(input="data.csv",   # pk dataset, which is formated as NONMEM input dataset
                      modeltype='basic_pk',        # basic pk models
                      administration='oral',       # oral PK
                      cl_init=30,                  # initial value of clearance
                      vc_init=100,                 # initial value of volume of distribution
                      mat_init=0.3,                # initial value of mean absorption time, for 1st order absorption, MAT = 1/KA
                      strategy='default',          # The default run order: structural, iiv, residual, iov, allometry, covariate
                      allometric_variable='WT',    # the column of body weight for allometric scaling
                      occasion='VISI',             # the column of occasion for IOV modeling
                      search_space='LET(CATEGORICAL, [SEX, NYHA,COMP,ACE,DIG,DIU]); LET(CONTINUOUS, [AGE,RF]);COVARIATE?(@IIV,@CONTINUOUS,[LIN,EXP]);COVARIATE?(@IIV,@CATEGORICAL, CAT)')

```

Gives error

```
Full stack:
AttributeError: 'NoneType' object has no attribute 'modes'Run `reticulate::py_last_error()` for details.AttributeError'NoneType' object has no attribute 'modes'c("  File \"/<install-dir>/pharmpy-core/1.0.1-foss-2023a/lib/python3.11/site-packages/pharmpy/tools/amd/run.py\", line 216, in run_amd\n    to_be_skipped = validate_input(**args)\n                    ^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/<install-dir>/pharmpy-core/1.0.1-foss-2023a/lib/python3.11/site-packages/pharmpy/internals/fn/type.py\", line 60, in _wrapped\n    return fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^\n", "  File \"/<install-dir>/pharmpy-core/1.0.1-foss-2023a/lib/python3.11/site-packages/pharmpy/tools/amd/run.py\", line 1194, in validate_input\n    if administration == \"oral\" and \"INST\" in (a.name for a in ss_mfl.absorption.modes):\n                                                               ^^^^^^^^^^^^^^^^^^^^^^^\n"
)Traceback (most recent call last):
  File "/<install-dir>/pharmpy-core/1.0.1-foss-2023a/lib/python3.11/site-packages/pharmpy/tools/amd/run.py", line 216, in run_amd
    to_be_skipped = validate_input(**args)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/<install-dir>/pharmpy-core/1.0.1-foss-2023a/lib/python3.11/site-packages/pharmpy/internals/fn/type.py", line 60, in _wrapped
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/<install-dir>/pharmpy-core/1.0.1-foss-2023a/lib/python3.11/site-packages/pharmpy/tools/amd/run.py", line 1194, in validate_input
    if administration == "oral" and "INST" in (a.name for a in ss_mfl.absorption.modes):
                                                               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'modes'
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.AttributeError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(input = "data.csv", modeltype = "basic_pk", administration = "oral", cl_init = 30, vc_init = 100, mat_init = 0.3, strategy = "default", allometric_variable = "WT", occasion = "VISI", search_space = "LET(CATEGORICAL, [SEX, NYHA,COMP,ACE,DIG,DIU]); LET(CONTINUOUS, [AGE,RF]);COVARIATE?(@IIV,@CONTINUOUS,[LIN,EXP]);COVARIATE?(@IIV,@CATEGORICAL, CAT)"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(input = "data.csv", modeltype = "basic_pk", administration = "oral", 
    cl_init = 30, vc_init = 100, mat_init = 0.3, strategy = "default", allometric_variable = "WT", occasion = "VISI", search_space = "LET(CATEGORICAL, [SEX, NYHA,COMP,ACE,DIG,DIU]); LET(CONTINUOUS, [AGE,RF]);COVARIATE?(@IIV,@CONTINUOUS,[LIN,EXP]);COVARIATE?(@IIV,@CATEGORICAL, CAT)"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.0.1'1.0.1'Pharmpy version: 1.0.1
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!
```

**Comment by stellabelin** [comment]
Hi! Thanks for reporting this! This bug was fixed in version 1.1.0 (previous issue here: https://github.com/pharmpy/pharmpy/issues/3113). To solve this, you can either upgrade the Pharmpy version or specify the full search space for the structural model as well. You can see the default search space for the structural model here: https://pharmpy.github.io/latest/amd_pk.html#structural
