### ISSUE TITLE
Validation input check issue when running AMD

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmr#183]
E.g.:

```
dataset_path <- 'path/to/dataset'
run_amd(dataset_path)
```

Raises the following:
```
symengine.lib.symengine_wrapper.SympifyError: sympy2symengine: Cannot convert 'None' (of type <class 'NoneType'>) to a symengine type.
Run `reticulate::py_last_error()` for details.SympifyErrorsympy2symengine: Cannot convert 'None' (of type <class 'NoneType'>) to a symengine type.c("  File \"/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/tools/amd/run.py\", line 200, in run_amd\n    model = create_basic_pk_model(\n            ^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/modeling/basic_models.py\", line 145, in create_basic_pk_model\n    model = create_joint_distribution(model, [eta_cl_name, eta_vc_name])\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/modeling/parameter_variability.py\", line 1094, in create_joint_distribution\n    model = model.replace(parameters=Parameters.create(pset_new), random_variables=all_rvs)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/model/model.py\", line 326, in replace\n    parameters = Model._canonicalize_parameter_estimates(parameters, random_variables)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/model/model.py\", line 173, in _canonicalize_parameter_estimates\n    if not rvs.validate_parameters(inits):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/model/random_variables.py\", line 761, in validate_parameters\n    sigma = sigma.subs(parameter_values)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/basic/matrix.py\", line 57, in subs\n    return Matrix(self._m.subs(d))\n                  ^^^^^^^^^^^^^^^\n", 
"  File \"symengine_wrapper.pyx\", line 3949, in symengine.lib.symengine_wrapper.DenseMatrixBase.subs\n", "  File \"symengine_wrapper.pyx\", line 805, in symengine.lib.symengine_wrapper.get_dict\n", "  File \"symengine_wrapper.pyx\", line 729, in symengine.lib.symengine_wrapper._DictBasic.add\n", "  File \"symengine_wrapper.pyx\", line 534, in symengine.lib.symengine_wrapper.sympify\n", "  File \"symengine_wrapper.pyx\", line 579, in symengine.lib.symengine_wrapper._sympify\n", "  File \"symengine_wrapper.pyx\", line 500, in symengine.lib.symengine_wrapper.sympy2symengine\n"
)Traceback (most recent call last):
  File "/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/tools/amd/run.py", line 200, in run_amd
    model = create_basic_pk_model(
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/modeling/basic_models.py", line 145, in create_basic_pk_model
    model = create_joint_distribution(model, [eta_cl_name, eta_vc_name])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/modeling/parameter_variability.py", line 1094, in create_joint_distribution
    model = model.replace(parameters=Parameters.create(pset_new), random_variables=all_rvs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/model/model.py", line 326, in replace
    parameters = Model._canonicalize_parameter_estimates(parameters, random_variables)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/model/model.py", line 173, in _canonicalize_parameter_estimates
    if not rvs.validate_parameters(inits):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/model/random_variables.py", line 761, in validate_parameters
    sigma = sigma.subs(parameter_values)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stella/anaconda3/envs/pharmpy_devel/lib/python3.11/site-packages/pharmpy/basic/matrix.py", line 57, in subs
    return Matrix(self._m.subs(d))
                  ^^^^^^^^^^^^^^^
  File "symengine_wrapper.pyx", line 3949, in symengine.lib.symengine_wrapper.DenseMatrixBase.subs
  File "symengine_wrapper.pyx", line 805, in symengine.lib.symengine_wrapper.get_dict
  File "symengine_wrapper.pyx", line 729, in symengine.lib.symengine_wrapper._DictBasic.add
  File "symengine_wrapper.pyx", line 534, in symengine.lib.symengine_wrapper.sympify
  File "symengine_wrapper.pyx", line 579, in symengine.lib.symengine_wrapper._sympify
  File "symengine_wrapper.pyx", line 500, in symengine.lib.symengine_wrapper.sympy2symengine
symengine.lib.symengine_wrapper.SympifyError: sympy2symengine: Cannot convert 'None' (of type <class 'NoneType'>) to a symengine type.
py_call_impl(callable, call_args$unnamed, call_args$named)c("symengine.lib.symengine_wrapper.SympifyError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(dataset_path), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(dataset_path), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.2.0
'1.2.0'
Pharmpy version: 1.2.0
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!
```

**Comment by stellabelin** [comment]
Possibly fixed after AMD input validation refactor.
