### ISSUE TITLE
Error message during run_modelsearch

### ISSUE THREAD

**Issue by schaedeli** [pharmpy/pharmr#67]
Hi
I had the following error mesages during modelsearch run:

```
sp4 <- "ABSORPTION([ZO,SEQ-ZO-FO]);LAGTIME();TRANSITS([10],*);PERIPHERALS(1)"
res_modelsearch <- run_modelsearch("modelsearch", 
                            model=input_model,
                            search_space=sp4, 
                            algorithm="reduced_stepwise", 
                            rankfunc="bic", 
                            iiv_strategy=3)
```

```
C:\PROGRA~1\Python39\lib\site-packages\distributed\node.py:160: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 65519 instead
  warnings.warn(
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:14: UserWarning: modelsearch_candidate21: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:14: UserWarning: modelsearch_candidate22: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
distributed.worker - WARNING - Compute Failed
Function:  post_process_results
args:      ('bic', 'modelsearch', <Pharmpy model object run1>, <Pharmpy model object modelsearch_candidate1>, <Pharmpy model object modelsearch_candidate2>, <Pharmpy model object modelsearch_candidate3>, <Pharmpy model object modelsearch_candidate4>, <Pharmpy model object modelsearch_candidate5>, <Pharmpy model object modelsearch_candidate6>, <Pharmpy model object modelsearch_candidate7>, <Pharmpy model object modelsearch_candidate8>, <Pharmpy model object modelsearch_candidate9>, <Pharmpy model object modelsearch_candidate10>, <Pharmpy model object modelsearch_candidate11>, <Pharmpy model object modelsearch_candidate12>, <Pharmpy model object modelsearch_candidate13>, <Pharmpy model object modelsearch_candidate14>, <Pharmpy model object modelsearch_candidate15>, <Pharmpy model object modelsearch_candidate16>, <Pharmpy model object modelsearch_candidate17>, <Pharmpy model object modelsearch_candidate18>, <Pharmpy model object modelsearch_candidate19>, <Pharmpy model object modelsearch_candidate20
kwargs:    {}
Exception: TypeError("'>=' not supported between instances of 'numpy.ndarray' and 'str'")

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: '>=' not supported between instances of 'numpy.ndarray' and 'str' 

```
1. Error/warning related to the nodes:  "UserWarning: Port 8787 is already in use..." Is this expected behaviour or a bug? Does it relate to PharmPy or rather to a local server issue?
2. UserWarning: modelsearch_candidate22: Could not update initial estimates, using original estimates ... - Is it expected, what does it mean? 
3. Function:  post_process_results - the results.csv file is not produced. Is this a known issue?
#summarize the results
res_modelsearch$summary_tool
the results were not produced, and no object res_modelsearch was created

**Comment by stellabelin** [comment]
Hi!

1. The warning is related to the pacakge we use for running the workflows, by default it uses port 8787 which Rstudio is occupying. The warning is basically saying that it uses another one, which is okay. However, it should not reach the user, I've added an issue here: https://github.com/pharmpy/pharmpy/issues/840
2. This is if one of the submodels fail and it tries to update inits (maybe there are NaNs in the results etc), however since the warning is not specific maybe it's not very helpful by itself, I have made a note to look over if this can be made clearer.
3. This error is the one causing the crash, it's difficult to say what's causing it. Do you get this behavior on a smaller search space on the same dataset?

**Comment by schaedeli** [comment]
Hi Stella
thanks for looking into this. 
ad 3: I have run the same modelsearch before, i.e. same input_model and initial estimates, with a different, more narrow search_space:

```
sp <- "TRANSITS([1,3],*);PERIPHERALS(1..2)"

#trigger automated model search
res_modelsearch <- run_tool("modelsearch", 
                            model=input_model,
                            search_space=sp, 
                            algorithm="reduced_stepwise", 
                            rankfunc="bic", 
                            iiv_strategy=3)

```
That previous modelsearch generated the results.csv as expected, and the results could be retrieved with from res_modelsearch$summary_tool.

Kind Regards,
Franziska

**Comment by stellabelin** [comment]
Hi again! It's difficult to say what is causing this issue, furthermore the function that does this has been refactored since the time this issue was filed. Is it possible to rerun it and see if the same issue occurs? Or to send the modelsearch-directory (dataset is not needed) and I could try to recreate it?

**Comment by schaedeli** [comment]
Hi Stella
I can rerun that specific modelsearch to check. I guess the error will no longer appear.
I'll let you know.

**Comment by schaedeli** [comment]
Hi again
I have tried to re-run the modelsearch with the same searchspace `sp4 <- "ABSORPTION([ZO,SEQ-ZO-FO]);LAGTIME();TRANSITS([10],*);PERIPHERALS(1)",` and still do not get back the results.

![Snag_57c3904](https://user-images.githubusercontent.com/106077991/186105270-bba0cafe-b8ba-4a1a-8a8c-42f4079be631.png)
.

Questions:

1. Part of the error message appears to point to the missing `rank_type` information, although, according to the help file, the default is "bic". Does the tool need the explicit argument for rank_type?
2. Is there a way to re-start the modelsearch, based on the 21 candidate models already completed? - As the full modelsearch takes several hours, it would not be efficient to re-run the whole search just to obtain the results.
3. There were 21 candidate models returned with NONMEM results files. In the previous run in May that triggered this issue initially, 24 candidate models were returned with NONMEM results files (but no results.json and results.csv) - Could that be a hint for localizing the issue?
4. Is it possible to retrieve the results from the available runs using a PharmPy command ?

**Comment by stellabelin** [comment]
Hi! Thank you for checking this! Regarding your questions:

1. The new argument name is `rank_type` (rather than `rankfunc`), but the tool doesn't need it to be stated explicitly, it should use `bic` unless otherwise specified. Here I think the issue is that you have `"modelsearch"` as your first argument. Since `run_modelsearch` doesn't have that argument, it will interpret this as your `rank_type`. Of course, this error makes no sense to a user, and we have an issue regarding input checking here: https://github.com/pharmpy/pharmpy/issues/1032
2. There is an option to resume a tool, but there have been issues due to how parameter names are configured (issue: https://github.com/pharmpy/pharmpy/issues/919). If you want to try, you can run this: `res <- run_tool('modelsearch',  ..., resume=TRUE)`
3. I think this is due to the fact that we fixed a bug in `reduced_stepwise` where it created too many models (this issue: https://github.com/pharmpy/pharmpy/issues/694), it was fixed in 0.75.0. If you want you could send me the modelsearch-directory and I can double check (datasets not needed)
4. Do you mean reread in the .json to get all the dataframes in R? Or read in e.g. all models and their result files?

**Comment by schaedeli** [comment]
Hi again, thanks for looking into this.
And thanks for pointing me to the error in the `run_modelsearch()` tool, which happened during copy-paste for re-testing, and I didn't pay attention to update all arguments.

ad 1) - I guess the issue was in using inappropriate arguments in this case. - Sorry to bother you with this, my mistake. So let me re-run the task one more time with hopefully correct arguments:
```
sp4 <- "ABSORPTION([ZO,SEQ-ZO-FO]);LAGTIME();TRANSITS([10],*);PERIPHERALS(1)"
res_modelsearch <- 
  run_modelsearch(search_space=sp4,
                  algorithm='reduced_stepwise',
                  model=input_model,
                  iiv_strategy='absorption_delay',
                  rank_type='bic',
                  cutoff=NULL)
```
I will let you know the outcome.

ad 2) - Thanks, I will try it out

ad 3) - I understand. No need to spend time on sharing the modelsearch directory for now.

ad 4) - I was just wondering if there is a way to summarize the results from the modelsearch directory, where all candidate models were run, but no results.json and results.csv files produced.

Thanks!

**Comment by schaedeli** [comment]
Hi again!
The above task has now completed, 21 candidate models ran, but the results summary is still not produced. The error messages appear a bit different though (see below). This has happened to me only with that specific search_space (which I used for testing purpose only, not scientifically driven).

Would it help to share the modelsearch_dir folder?

```
sp4 <- "ABSORPTION([ZO,SEQ-ZO-FO]);LAGTIME();TRANSITS([10],*);PERIPHERALS(1)"
res_modelsearch <- 
  run_modelsearch(search_space=sp4,
                  algorithm='reduced_stepwise',
                  model=input_model,
                  iiv_strategy='absorption_delay',
                  rank_type='bic',
                  cutoff=NULL)
```

```
Task was destroyed but it is pending!
task: <Task pending name='Task-72' coro=<Worker.execute() running at C:\PROGRA~1\Python39\lib\site-packages\distributed\worker.py:2955> wait_for=<Future pending cb=[coroutine.<locals>.wrapper.<locals>.<lambda>() at C:\PROGRA~1\Python39\lib\site-packages\tornado\gen.py:251, <TaskWakeupMethWrapper object at 0x000002C1CA08E490>()]> cb=[IOLoop.add_future.<locals>.<lambda>() at C:\PROGRA~1\Python39\lib\site-packages\tornado\ioloop.py:688]>
Task was destroyed but it is pending!
task: <Task pending name='Task-167' coro=<Worker.execute() running at C:\PROGRA~1\Python39\lib\site-packages\distributed\worker.py:2955> wait_for=<Future pending cb=[coroutine.<locals>.wrapper.<locals>.<lambda>() at C:\PROGRA~1\Python39\lib\site-packages\tornado\gen.py:251, <TaskWakeupMethWrapper object at 0x000002C1CCB20EE0>()]> cb=[IOLoop.add_future.<locals>.<lambda>() at C:\PROGRA~1\Python39\lib\site-packages\tornado\ioloop.py:688]>
Task was destroyed but it is pending!
task: <Task pending name='Task-168' coro=<Worker.execute() running at C:\PROGRA~1\Python39\lib\site-packages\distributed\worker.py:2955> wait_for=<Future pending cb=[coroutine.<locals>.wrapper.<locals>.<lambda>() at C:\PROGRA~1\Python39\lib\site-packages\tornado\gen.py:251, <TaskWakeupMethWrapper object at 0x000002C1CCA694F0>()]> cb=[IOLoop.add_future.<locals>.<lambda>() at C:\PROGRA~1\Python39\lib\site-packages\tornado\ioloop.py:688]>
distributed.comm.inproc - WARNING - Closing dangling queue in <InProc  local=inproc://10.136.106.81/9400/12 remote=inproc://10.136.106.81/9400/20>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x000002C1A807E040>>, <Task finished name='Task-155163' coro=<SpecCluster._correct_state_internal() done, defined at C:\PROGRA~1\Python39\lib\site-packages\distributed\deploy\spec.py:327> exception=OSError('Timed out trying to connect to inproc://10.136.106.81/9400/12 after 10 s')>)
Traceback (most recent call last):
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\comm\inproc.py", line 312, in connect
    await conn_req.conn_event.wait()
  File "C:\PROGRA~1\Python39\lib\asyncio\locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1\Python39\lib\asyncio\tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\comm\core.py", line 286, in connect
    comm = await asyncio.wait_for(
  File "C:\PROGRA~1\Python39\lib\asyncio\tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PROGRA~1\Python39\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "C:\PROGRA~1\Python39\lib\site-packages\tornado\ioloop.py", line 765, in _discard_future_result
    future.result()
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\deploy\cluster.py", line 439, in __aexit__
    await f
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\deploy\spec.py", line 419, in _close
    await self._correct_state()
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\deploy\spec.py", line 334, in _correct_state_internal
    await self.scheduler_comm.retire_workers(workers=list(to_close))
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\core.py", line 795, in send_recv_from_rpc
    comm = await self.live_comm()
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\core.py", line 753, in live_comm
    comm = await connect(
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\comm\core.py", line 310, in connect
    raise OSError(
OSError: Timed out trying to connect to inproc://10.136.106.81/9400/12 after 10 s
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\schaedef\\AppData\\Local\\Temp\\7\\tmpe09jraow\\dask-worker-space\\worker-i0odn23x.dirlock'

Detailed traceback:
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\wrap.py", line 46, in _func
    return run_tool(tool_name, *args, **kwargs)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\run.py", line 167, in run_tool
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\workflows\execute.py", line 58, in execute_workflow
    res = dispatcher.run(workflow)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\workflows\dispatchers\local_dask.py", line 40, in run
    res = client.get(dsk_optimized, 'results')
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\utils.py", line 94, in __exit__
    self.cleanup()
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\utils.py", line 98, in cleanup
    self
```

**Comment by pharmpy-dev-123** [comment]
Moving this to Pharmpy since this does not seem to have anything to do with R.
